/**
 * 所有会进入正式扫描结果的规则 ID。
 *
 * DEEPSCAN_FAILED 是扫描框架的兜底错误，不是具体规则，故不进入处置矩阵。
 * 新增或删除规则时，action-matrix.test.mjs 会强制本列表与源码保持一一对应。
 */
export const RULE_IDS = [
  // Claude Code
  "CLAUDE_LOCAL_BASE_URL",
  "CLAUDE_UNKNOWN_BASE_URL",
  "CLAUDE_INSECURE_HTTP",
  "CLAUDE_PLAINTEXT_TOKEN",
  "CLAUDE_API_KEY_HELPER",
  "CLAUDE_BYPASS_PERMISSIONS",
  "CLAUDE_DANGEROUS_ALLOW",
  "CLAUDE_HOOKS_PRESENT",
  "CLAUDE_ENABLE_ALL_PROJECT_MCP",
  "CLAUDE_MCP_REMOTE",
  "CLAUDE_MCP_STDIO",
  "CLAUDE_MCP_SECRET_ENV",
  "CLAUDE_PARSE_FAILED",

  // Codex
  "CODEX_CUSTOM_PROVIDER",
  "CODEX_INSECURE_HTTP",
  "CODEX_PLAINTEXT_API_KEY",
  "CODEX_MCP_REMOTE",
  "CODEX_MCP_STDIO",
  "CODEX_MCP_SECRET_ENV",
  "CODEX_TRUSTED_PROJECTS",
  "CODEX_LOCAL_PROXY",
  "CODEX_PARSE_FAILED",

  // CC Switch
  "CCSWITCH_SCHEMA_UNKNOWN",
  "CCSWITCH_UNKNOWN_BASE_URL",
  "CCSWITCH_RELAY_ENDPOINT",
  "CCSWITCH_INSECURE_HTTP",
  "CCSWITCH_PLAINTEXT_KEY",
  "CCSWITCH_SHARED_KEY",
  "CCSWITCH_PROXY_ENABLED",
  "CCSWITCH_PROXY_FAILOVER_UNKNOWN",
  "CCSWITCH_PARSE_FAILED",

  // OpenCode
  "OPENCODE_CUSTOM_PROVIDER",
  "OPENCODE_INSECURE_HTTP",
  "OPENCODE_PLAINTEXT_KEY",
  "OPENCODE_BASH_UNRESTRICTED",
  "OPENCODE_PERMISSION_WILDCARD",
  "OPENCODE_SHARE_AUTO",
  "OPENCODE_AUTOUPDATE_ON",
  "OPENCODE_MCP_REMOTE",
  "OPENCODE_MCP_LOCAL",
  "OPENCODE_MCP_SECRET_ENV",
  "OPENCODE_PARSE_FAILED",

  // Gemini CLI
  "GEMINI_PLAINTEXT_ENV_KEY",
  "GEMINI_MCP_TRUST_BYPASS",
  "GEMINI_MCP_REMOTE",
  "GEMINI_MCP_STDIO",
  "GEMINI_MCP_SECRET_ENV",
  "GEMINI_SHELL_NO_SANDBOX",
  "GEMINI_AUTH_MODE",
  "GEMINI_PARSE_FAILED",

  // OpenClaw
  "OPENCLAW_CHANNEL_PLAINTEXT_SECRET",
  "OPENCLAW_CHANNEL_PLAINTEXT_TOKEN",
  "OPENCLAW_GATEWAY_PLAINTEXT_TOKEN",
  "OPENCLAW_GATEWAY_EXPOSED_BIND",
  "OPENCLAW_TAILSCALE_EXPOSURE",
  "OPENCLAW_AGENT_WORKSPACE_OVERLAP",
  "OPENCLAW_UNKNOWN_PLUGIN_SOURCE",
  "OPENCLAW_SERVICE_ENV_PRESENT",
  "OPENCLAW_PARSE_FAIL",

  // 跨 Agent 与项目级规则
  "XAGENT_SHARED_PROXY",
  "XAGENT_SHARED_ENDPOINT",
  "PROJECT_SENSITIVE_FILE",
  "PROJECT_SENSITIVE_SCAN_TRUNCATED",
] as const;

export type RuleId = (typeof RULE_IDS)[number];
